-- Derived from strath-sdr/rfsoc_ofdm ofdm_tx_v0_5 (HDL Coder output, BSD-3-Clause).
-- Modified: the internal random data source is replaced by the ext_data/ext_pop
-- ports so that a user bit stream is modulated instead of PRBS data.
-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/OFDM_Tx_HW/ofdm_txs_dut.vhd
-- Created: 2023-10-17 14:27:03
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_txs_dut
-- Source Path: ofdm_tx/ofdm_txs_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_txs_dut IS
  PORT( clk                               :   IN    std_logic;
        ext_data                          :   IN    std_logic_vector(9 DOWNTO 0);  -- external symbol bits
        ext_pop                           :   OUT   std_logic;  -- one pulse per consumed symbol
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        modScheme                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        enable                            :   IN    std_logic;  -- ufix1
        gain                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        data                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        valid                             :   OUT   std_logic  -- ufix1
        );
END ofdm_txs_dut;


ARCHITECTURE rtl OF ofdm_txs_dut IS

  -- Component Declarations
  COMPONENT ofdm_txs_src_OFDMTx
    PORT( clk                             :   IN    std_logic;
          ext_data                        :   IN    std_logic_vector(9 DOWNTO 0);
          ext_pop                         :   OUT   std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          modScheme                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          enable                          :   IN    std_logic;  -- ufix1
          gain                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          data                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          valid                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ofdm_txs_src_OFDMTx
    USE ENTITY work.ofdm_txs_src_OFDMTx(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL enable_sig                       : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL data_sig                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL valid_sig                        : std_logic;  -- ufix1

BEGIN
  u_ofdm_tx_src_OFDMTx : ofdm_txs_src_OFDMTx
    PORT MAP( clk => clk,
              ext_data => ext_data,
              ext_pop => ext_pop,
              clk_enable => enb,
              reset => reset,
              modScheme => modScheme,  -- ufix32
              enable => enable_sig,  -- ufix1
              gain => gain,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              data => data_sig,  -- ufix32
              valid => valid_sig  -- ufix1
              );

  enable_sig <= enable;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  data <= data_sig;

  valid <= valid_sig;

END rtl;

