-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/OFDM_Rx_HW/ofdm_rx_src_SymbolCounter_block.vhd
-- Created: 2023-10-17 14:31:33
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_rx_src_SymbolCounter_block
-- Source Path: OFDM_Rx_HW/OFDMRx/PhaseTracking_2/PilotCtrlGen/SymbolCounter
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_rx_src_SymbolCounter_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_12_0                        :   IN    std_logic;
        ValidIn                           :   IN    std_logic;
        preambleValidIn                   :   IN    std_logic;
        Symbl_cnt                         :   OUT   std_logic_vector(6 DOWNTO 0)  -- ufix7
        );
END ofdm_rx_src_SymbolCounter_block;


ARCHITECTURE rtl OF ofdm_rx_src_SymbolCounter_block IS

  -- Signals
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Relational_Operator1_relop1      : std_logic;
  SIGNAL delayMatch_reg                   : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Relational_Operator1_out1        : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(6 DOWNTO 0);  -- ufix7

BEGIN
  -- reset counter when preamble detected

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        Delay1_out1 <= preambleValidIn;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  
  Relational_Operator1_relop1 <= '1' WHEN preambleValidIn < Delay1_out1 ELSE
      '0';

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        delayMatch_reg(0) <= Relational_Operator1_relop1;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Relational_Operator1_out1 <= delayMatch_reg(1);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        Delay_out1 <= ValidIn;
      END IF;
    END IF;
  END PROCESS Delay_process;


  
  Relational_Operator_relop1 <= '1' WHEN ValidIn < Delay_out1 ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 126
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#00#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        IF Relational_Operator1_out1 = '1' THEN 
          HDL_Counter_out1 <= to_unsigned(16#00#, 7);
        ELSIF Relational_Operator_relop1 = '1' THEN 
          IF HDL_Counter_out1 >= to_unsigned(16#7E#, 7) THEN 
            HDL_Counter_out1 <= to_unsigned(16#00#, 7);
          ELSE 
            HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#01#, 7);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  Symbl_cnt <= std_logic_vector(HDL_Counter_out1);

END rtl;

