-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/OFDM_Rx_HW/ofdm_rx_src_Frame_Detection_Valid_Gen.vhd
-- Created: 2023-10-17 14:31:33
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_rx_src_Frame_Detection_Valid_Gen
-- Source Path: OFDM_Rx_HW/OFDMRx/Synchronisation/FrameDetect/Frame Detection Valid Gen
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_rx_src_Frame_Detection_Valid_Gen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_12_0                        :   IN    std_logic;
        enable                            :   IN    std_logic;
        frameDet                          :   OUT   std_logic
        );
END ofdm_rx_src_Frame_Detection_Valid_Gen;


ARCHITECTURE rtl OF ofdm_rx_src_Frame_Detection_Valid_Gen IS

  -- Component Declarations
  COMPONENT ofdm_rx_src_Frame_Detection
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_12_0                      :   IN    std_logic;
          enable                          :   IN    std_logic;
          frameDet                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ofdm_rx_src_Frame_Detection
    USE ENTITY work.ofdm_rx_src_Frame_Detection(rtl);

BEGIN
  -- A valid is generated for the duration of the OFDM Frame

  u_Frame_Detection : ofdm_rx_src_Frame_Detection
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_12_0 => enb_1_12_0,
              enable => enable,
              frameDet => frameDet
              );

END rtl;

