-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/OFDM_Tx_HW/ofdm_tx_src_ControlSignalGenerator.vhd
-- Created: 2023-10-17 14:26:57
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_tx_src_ControlSignalGenerator
-- Source Path: OFDM_Tx_HW/OFDMTx/ControlSignalGenerator
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_tx_src_ControlSignalGenerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_12_0                        :   IN    std_logic;
        enable                            :   IN    std_logic;
        dataValid                         :   OUT   std_logic;
        preambleValid                     :   OUT   std_logic;
        dataReady                         :   OUT   std_logic;
        PilotValid                        :   OUT   std_logic
        );
END ofdm_tx_src_ControlSignalGenerator;


ARCHITECTURE rtl OF ofdm_tx_src_ControlSignalGenerator IS

  -- Component Declarations
  COMPONENT ofdm_tx_src_Control_Signal_Generator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_12_0                      :   IN    std_logic;
          enable                          :   IN    std_logic;
          preambleValid                   :   OUT   std_logic;
          dataValid                       :   OUT   std_logic;
          dataReady                       :   OUT   std_logic;
          pilotValid                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ofdm_tx_src_Control_Signal_Generator
    USE ENTITY work.ofdm_tx_src_Control_Signal_Generator(rtl);

  -- Signals
  SIGNAL pilotValid_1                     : std_logic;

BEGIN
  u_Control_Signal_Generator : ofdm_tx_src_Control_Signal_Generator
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_12_0 => enb_1_12_0,
              enable => enable,
              preambleValid => preambleValid,
              dataValid => dataValid,
              dataReady => dataReady,
              pilotValid => pilotValid_1
              );

  PilotValid <= pilotValid_1;

END rtl;

